include: package:lints/recommended.yaml

linter:
  rules:
    - prefer_single_quotes
    - avoid_print
    - prefer_final_locals
    - prefer_final_fields
    - avoid_unused_constructor_parameters
    - prefer_const_constructors
    - prefer_const_declarations
